spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: qwerty123
    url: jdbc:mysql://localhost/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
  application:
    name: product
  jpa:
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/